#!/bin/bash

source .env

HOST_CACHE_DIR=$PWD/var/docker-cache/.npm
CONTAINER_CACHE_DIR=/tmp/.npm

mkdir -p ${HOST_CACHE_DIR}

docker run \
    --rm \
    --interactive \
    --tty \
    --init \
    --user "$UID:$(id -g)" \
    --volume "$PWD:/srv/app" \
    --volume "$HOME:$HOME" \
    --volume "${HOST_CACHE_DIR}:${CONTAINER_CACHE_DIR}" \
	--expose=9000 \
    --publish=9000:9000 \
    --env npm_config_cache="${CONTAINER_CACHE_DIR}" \
    --workdir /srv/app \
    ${NODE_IMAGE} \
    npm "$@"
